version: '3.8'

services:
  postgres:
    image: postgres:13
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nestapp
      POSTGRES_DB: nestapp
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/pg:/data/postgres